import {BellOutlined, LockOutlined, SaveOutlined, SettingOutlined} from '@ant-design/icons'
import {Button, Card, Divider, Form, Input, message, Space, Switch, Tabs} from 'antd'

export default function SettingsPage() {
    const [form] = Form.useForm()
    const saveSettings = () => message.success('系统设置已保存（仅在本次演示中生效）')
    const general = <Card className="settings-card"><Form form={form} layout="vertical" initialValues={{name: 'OneOps 运营管理台', domain: 'https://ops.example.com', timezone: 'Asia/Shanghai', language: 'zh-CN'}} onFinish={saveSettings}><Form.Item name="name" label="系统名称" rules={[{required: true, message: '请输入系统名称'}]}><Input /></Form.Item><Form.Item name="domain" label="访问域名" rules={[{required: true, type: 'url', message: '请输入有效 URL'}]}><Input /></Form.Item><Form.Item name="timezone" label="时区"><Input disabled /></Form.Item><Divider /><Button type="primary" htmlType="submit" icon={<SaveOutlined />}>保存基础设置</Button></Form></Card>
    const notification = <Card className="settings-card"><Space direction="vertical" size={16} className="page-stack"><div className="setting-switch"><div><b>站内通知</b><span>接收待办、审核和业务状态变更提醒</span></div><Switch defaultChecked /></div><div className="setting-switch"><div><b>邮件摘要</b><span>工作日 09:00 将昨日运营摘要发送至管理员邮箱</span></div><Switch defaultChecked /></div><div className="setting-switch"><div><b>异常订单提醒</b><span>订单取消、超时和金额异常时即时通知</span></div><Switch /></div><Button type="primary" icon={<SaveOutlined />} onClick={saveSettings}>保存通知设置</Button></Space></Card>
    const security = <Card className="settings-card"><Space direction="vertical" size={16} className="page-stack"><div className="setting-switch"><div><b>双重验证</b><span>管理员登录时要求额外进行身份验证</span></div><Switch defaultChecked /></div><div className="setting-switch"><div><b>登录异常检测</b><span>检测到异常设备或地点时自动发送提醒</span></div><Switch defaultChecked /></div><Button type="primary" icon={<SaveOutlined />} onClick={saveSettings}>保存安全设置</Button></Space></Card>
    return <Tabs className="settings-tabs" defaultActiveKey="general" items={[{key: 'general', label: <span><SettingOutlined />基础设置</span>, children: general}, {key: 'notification', label: <span><BellOutlined />通知设置</span>, children: notification}, {key: 'security', label: <span><LockOutlined />安全设置</span>, children: security}]} />
}
